### ISSUE TITLE
Url is not a valid Jenkins server

### ISSUE THREAD

**Issue by tomkuijsten** [tomkuijsten/vsjenkinsmanager#40]
Thanks for the Visual Studio plugin for Jenkins. I am facing an issue. The Jenkin server URL that I am trying to connect is in the form of https:://{ab-jenkins1.companyname.com}. The server version "X-Jenkins" is 1.609.1. 
But the Url* edit box shows "Url is not a valid Jenkins server". Is there any check that I can do to figure out the problem ?

https://visualstudiogallery.msdn.microsoft.com/3471d451-c1f1-4273-b305-acf81e4f8b32

**Comment by tomkuijsten** [comment]
I've added a unittest project to test the retrieval of the X-Jenkins header, could you run the tests with your url (stored as a class variable in the test class).

I've also fixed two possible problems, increased the web request timeout and fixed a dispose problem.

**Comment by helenren** [comment]
Seems this issue is still there. I hit the same issue on my machine, where I am using https url and jenkins version is 1.638

**Comment by AlekKras** [comment]
Having the same issue
